version: "3.3"
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
        POSTGRES_DB: bellissimo
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
    - 5432:5432
