version: "3.3"
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
        POSTGRES_DB: bellissimo
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
    - 5432:5432

  api:
    build:
        context: .
    depends_on:
        - db
    environment:
        DATABASE_URL: postgresql://admin:admin@host.docker.internal:5432/bellissimo
        SECRET_KEY: 546a7c2ea25f65b9aabcac39c72c4c42cd01869f4d30eec1f2820bfdbaceb796
        ALGORITHM: HS256
        ACCESS_TOKEN_EXPIRE_MINUTES: 30
    command: uvicorn app.main:app --host=0.0.0.0 --port=8000
    ports:
        - "8000:8000"
      
    
